version: '3.1'

services:

  wildphoto-server:
    image: wildphoto-server:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    network_mode: "host"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    ports:
      - "3340:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wildphoto
      MYSQL_USER: wildphoto
      MYSQL_PASSWORD: wildphoto
      MYSQL_ROOT_PASSWORD: wildphoto
      LANG: C.UTF-8
